### ISSUE TITLE
Invalid Credentials Error during Login in example.js

### ISSUE THREAD

**Issue by NikeLaosClericus** [lesleyxyz/node-tile#1]
My email and password are definitely correct, but can't authenticate.
My password does contain a special character (%), if that matters?

```
node example.js 
/Projects/NodeJS/node_modules/node-tile/lib/esm/services/UserService.js:32
            throw Error(`Error code ${result_code}: ${result?.message}`);
                  ^

Error: Error code 1: Invalid credentials for email 'email@email.com', you have 15 login attempts left
    at UserService.handleError (/Projects/NodeJS/node_modules/node-tile/lib/esm/services/UserService.js:32:19)
    at UserService.login (/Projects/NodeJS/node_modules/node-tile/lib/esm/services/UserService.js:26:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Projects/NodeJS/example.js:6:1
```

**Comment by lesleyxyz** [comment]
Interesting.. I'll see if I can reproduce this issue

**Comment by NikeLaosClericus** [comment]
I'm so sorry, I did have my password wrong.
Working well, apologies again.
